name: Lint commit messages with commitlint

on:
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: severgroup-tt/actions-commit-linter-cli@v1.0.0
