name: Lint commit messages with commitlint

on:
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Set up GitHub Actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate commit message with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
        # run: npx commitlint --from HEAD~1 --to HEAD --verbose
