name: New release

on:
  push:
    tags:
      - 'v[0-9]+'

env:
  file_name: issie_data.txt
  path: ./
  artifact_name: artifact_1

jobs:

  commitlint:
    name: Test commit message with commitlint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Set up GitHub Actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate commit message with commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

  tests:
    name: Unit and e2e tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: npm ci
    - name: Install playwright
      run: npx playwright install
    - name: Build project
      run: npm run build
    - name: unit tests
      run: npm run test
    - name: e2e tests
      run: npm run e2e

  release:
    name: Create release
    needs: [commitlint, tests]
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest

    outputs:
      issue: ${{ steps.create-issue.outputs.number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
         token: ${{ github.token }}
         tag: ${{ github.ref_name }}
         writeToFile: false
      - name: Create an issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_CHANGELOG: ${{ steps.changelog.outputs.changes }}
          RELEASE_AUTHOR: ${{ github.actor }}
          RELEASE_NO: ${{ github.ref_name }}
          RELEASE_DATE: ${{ github.event.repository.updated_at}}
      - name: Create artifact data
        run:
          echo ${{ steps.create-issue.outputs.number }} > ${{ env.path }}${{ env.file_name }}
      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.path }}${{ env.file_name }}
          retention-days: 30

  deploy:
    name: Create build and deploy on gh-pages
    needs: [release]
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v3
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Deploy project with ph-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build

  close:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Close Release Issue after successful deploy
    needs: [deploy]
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub Actions
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.path }}
      - name: Read artifact
        id: getissue
        run: |
          value=`cat ${{ env.path }}${{ env.file_name }}`
          echo "issuie_num=$value" >> $GITHUB_ENV
      - name: Close issue
        run: |
          echo "${{ env.issuie_num }}"
          gh issue close ${{ env.issuie_num }}
